name: api
on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          run_install: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      # TODO: fix type
      # - name: Build API
      #   run: pnpm run build:api

      # - name: Deploy
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./packages/el-bot/docs
      #     force_orphan: true
